apiVersion: v1
kind: Service
metadata:
  name: vllm-service
  namespace: {{ .Values.llmd.namespace }}
  labels:
    llm-d.ai/model: ms-inference-scheduling-llm-d-modelservice
spec:
  selector:
    llm-d.ai/model: ms-inference-scheduling-llm-d-modelservice
  ports:
    - name: vllm
      port: 8200
      protocol: TCP
      targetPort: 8200
      nodePort: {{ .Values.vllmService.nodePort }}
  type: NodePort
