apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../default

patches:
- path: configmap-patch.yaml
  target:
    kind: ConfigMap
    name: workload-variant-autoscaler-variantautoscaling-config
- path: prometheus-patch.yaml
  target:
    kind: Deployment
    name: controller-manager

namespace: workload-variant-autoscaler-system
